function(add_hwlib_bmptk_target name path makefile)
    set(name ${name})
    set(path ${path})
    set(makefile ${makefile})
    add_subdirectory("${HCT}/Target_Maker" "${CMAKE_CURRENT_BINARY_DIR}/HCT/${name}")
endfunction()