
SEARCH += $(BMPTK)/targets/avr/include
SEARCH += $(BMPTK)/targets/cortex/stm32

get_defines:
	$(info    $(DEFINES))

get_libs:
	$(info    $(LIBS))

get_sources:
	$(info    $(SOURCES))

get_headers:
	$(info    $(HEADERS))

get_search:
	$(info    $(SEARCH))